- name: Deploy Backend Node.js App
  hosts: backend
  become: yes
  vars:
    backend_app_path: /home/ec2-user/backend-app
    backend_port: 3001
    local_backend_path: ../backend-app/

  tasks:
    - name: Enable NodeSource Node.js 20 repo
      shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        warn: false

    - name: Install Node.js and npm
      yum:
        name: nodejs
        state: present

    - name: Create backend app directory on remote
      file:
        path: "{{ backend_app_path }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy backend app files from control node
      copy:
        src: "{{ local_backend_path }}"
        dest: "{{ backend_app_path }}/"
        owner: ec2-user
        group: ec2-user
        mode: '0755'
        remote_src: no

    - name: Install backend app dependencies
      npm:
        path: "{{ backend_app_path }}"
        production: no

    - name: Start backend app in background
      shell: "nohup node server.js > backend.log 2>&1 &"
      args:
        chdir: "{{ backend_app_path }}"
      async: 0
      poll: 0
