---
- name: Setup Backend Node.js App
  hosts: backend
  become: true
  vars:
    app_dir: /home/ec2-user/backend-app
    node_version: 20

  tasks:

    - name: Install required packages
      ansible.builtin.yum:
        name:
          - curl
          - git
        state: present

    - name: Enable NodeSource Node.js 20 repo
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      ansible.builtin.yum:
        name: nodejs
        state: present

    - name: Create backend app directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: Copy backend app files
      ansible.builtin.copy:
        src: ../backend-app/
        dest: "{{ app_dir }}/"
        owner: ec2-user
        group: ec2-user
        mode: 0755
        remote_src: no

    - name: Install backend dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: "{{ app_dir }}"

    - name: Start backend app
      ansible.builtin.shell: |
        nohup node server.js > backend.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
