- hosts: backend
  become: yes
  vars:
    db_host: "10.0.4.82" # Matches db1 in inventory
    db_name: "backenddb"
    db_user: "backenduser"
    db_password: "backendpass123" # Store in Secrets Manager in production
  tasks:
    - name: Install Node.js
      dnf:
        name: nodejs
        state: present
      register: node_install
      failed_when: node_install.rc != 0

    - name: Install PM2
      npm:
        name: pm2
        global: yes
      when: node_install is success

    - name: Create app directory
      file:
        path: /app
        state: directory
        mode: '0755'

    - name: Copy backend app
      copy:
        src: ../backend-app
        dest: /app
        mode: '0644'

    - name: Install dependencies
      command: npm install pg
      args:
        chdir: /app
      register: npm_install
      failed_when: npm_install.rc != 0

    - name: Configure environment variables
      copy:
        content: |
          DB_HOST={{ db_host }}
          DB_NAME={{ db_name }}
          DB_USER={{ db_user }}
          DB_PASSWORD={{ db_password }}
        dest: /app/.env
        mode: '0600'

    - name: Start backend app with PM2
      command: pm2 start /app/server.js --name backend-app
      when: npm_install is success