---
- name: Configure Backend Node.js App
  hosts: backend
  become: yes
  vars:
    node_version: "20"

  tasks:
    - name: Ensure EPEL repo is enabled
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: Install required packages
      ansible.builtin.yum:
        name:
          - git
          - curl
        state: present

    - name: Add NodeSource Node.js 20 repo
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js 20 and npm
      ansible.builtin.yum:
        name: nodejs
        state: present

    - name: Install pm2 globally
      ansible.builtin.npm:
        name: pm2
        global: yes

    - name: Clone backend app repo
      ansible.builtin.git:
        repo: 'https://github.com/sahgul27/IAC-3tier.git'
        dest: /home/ec2-user/backend-app
        version: main
        force: yes

    - name: Install backend app dependencies
      ansible.builtin.shell: |
        npm install
      args:
        chdir: /home/ec2-user/backend-app

    - name: Start backend app with pm2
      ansible.builtin.shell: |
        pm2 start /home/ec2-user/backend-app/server.js --name backend-app --watch
      args:
        chdir: /home/ec2-user/backend-app
