---
- name: Deploy Backend App
  hosts: backend
  become: yes
  vars:
    backend_app_dir: /home/ec2-user/backend-app
    node_version: 20

  tasks:
    - name: Install Node.js 20 repo
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        warn: false

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Ensure backend app directory exists
      file:
        path: "{{ backend_app_dir }}"
        state: directory

    - name: Copy backend app files from control node
      copy:
        src: "../backend-app/"
        dest: "{{ backend_app_dir }}/"
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: Install backend app dependencies
      npm:
        path: "{{ backend_app_dir }}"
        production: yes

    - name: Start backend app with pm2
      ansible.builtin.shell: |
        npm install -g pm2
        pm2 start index.js --name backend
        pm2 save
      args:
        chdir: "{{ backend_app_dir }}"
