---
- name: Setup Backend Node.js App
  hosts: backend
  become: true
  vars:
    backend_app_dir: /home/ec2-user/backend-app
    node_port: 3000

  tasks:
    - name: Install EPEL repo (required for some dependencies)
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install curl and git
      ansible.builtin.yum:
        name:
          - curl
          - git
        state: present

    - name: Enable NodeSource Node.js 20 repo
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        warn: false

    - name: Install Node.js
      ansible.builtin.yum:
        name: nodejs
        state: present

    - name: Copy backend app to remote server
      ansible.builtin.copy:
        src: ../backend-app/
        dest: "{{ backend_app_dir }}"
        owner: ec2-user
        group: ec2-user
        mode: '0755'
      delegate_to: localhost

    - name: Install npm dependencies
      ansible.builtin.command: npm install
      args:
        chdir: "{{ backend_app_dir }}"

    - name: Start backend app using pm2
      ansible.builtin.shell: |
        npm install -g pm2
        pm2 start server.js --name backend-app --watch
        pm2 save
      args:
        chdir: "{{ backend_app_dir }}"
