---
- name: Setup PostgreSQL DB
  hosts: db
  become: true
  vars:
    db_name: backenddb
    db_user: backenduser
    db_pass: backendpass123

  tasks:
    - name: Enable PostgreSQL 15 module
      ansible.builtin.command: dnf module enable -y postgresql:15
      become: true

    - name: Install PostgreSQL server
      ansible.builtin.yum:
        name:
          - postgresql-server
          - postgresql-contrib
        state: present
      become: true

    - name: Initialize PostgreSQL database
      ansible.builtin.command: /usr/bin/postgresql-setup --initdb
      become: true

    - name: Ensure PostgreSQL is started and enabled
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
      become: true

    - name: Set PostgreSQL password for default user
      ansible.builtin.shell: |
        sudo -u postgres psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_pass }}';"
        sudo -u postgres psql -c "CREATE DATABASE {{ db_name }} OWNER {{ db_user }};"
        sudo -u postgres psql -c "ALTER USER {{ db_user }} WITH SUPERUSER;"
      args:
        warn: false
