- name: Deploy DB
  hosts: db
  become: yes
  vars:
    db_app_path: /home/ec2-user/db-app

  tasks:
    - name: Enable MariaDB repo
      yum_repository:
        name: MariaDB
        description: MariaDB Repo
        baseurl: http://yum.mariadb.org/10.6/rhel8-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
        state: present

    - name: Install MariaDB server
      yum:
        name: MariaDB-server
        state: present

    - name: Enable and start MariaDB service
      systemd:
        name: mariadb
        enabled: yes
        state: started
