---
- name: Setup PostgreSQL 15
  hosts: db
  become: true
  vars:
    db_user: backenduser
    db_name: backenddb
    db_pass: backendpass123

  tasks:

    - name: Install required packages
      ansible.builtin.yum:
        name:
          - wget
          - ca-certificates
        state: present

    - name: Add PostgreSQL 15 repo
      ansible.builtin.yum_repository:
        name: pgdg
        description: "PostgreSQL 15 repository"
        baseurl: https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-9-x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

    - name: Install PostgreSQL 15 server
      ansible.builtin.yum:
        name:
          - postgresql15
          - postgresql15-server
        state: present

    - name: Initialize PostgreSQL database
      ansible.builtin.command: /usr/pgsql-15/bin/postgresql-15-setup initdb
      args:
        creates: /var/lib/pgsql/15/data/PG_VERSION

    - name: Ensure PostgreSQL is running and enabled
      ansible.builtin.service:
        name: postgresql-15
        state: started
        enabled: true

    - name: Set PostgreSQL password for default user
      ansible.builtin.postgresql_user:
        name: postgres
        password: "{{ db_pass }}"

    - name: Create database user
      ansible.builtin.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        state: present

    - name: Create backend database
      ansible.builtin.postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        state: present
