---
- name: Deploy DB
  hosts: db
  become: yes
  vars:
    db_name: backenddb
    db_user: backenduser
    db_password: "backendpass123"

  tasks:
    - name: Ensure system is up to date
      yum:
        name: "*"
        state: latest
      ignore_errors: yes

    - name: Install PostgreSQL server
      yum:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: /usr/bin/postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        enabled: yes
        state: started

    - name: Ensure PostgreSQL Python libraries are installed
      yum:
        name: python3-psycopg2
        state: present

    - name: Create database for backend app
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create DB user for backend app
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}:ALL"
        state: present
