- hosts: db
  become: yes
  vars:
    db_name: "backenddb"
    db_user: "backenduser"
    db_password: "backendpass123"

  tasks:
    - name: Install PostgreSQL server and client
      yum:
        name:
          - postgresql
          - postgresql-server
          - postgresql-contrib
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Ensure PostgreSQL is started and enabled
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Update pg_hba.conf to allow password authentication
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: "host {{ db_name }} {{ db_user }} 0.0.0.0/0 md5"
        insertafter: "^# IPv4 local connections:"
      notify: Restart PostgreSQL

    - name: Create database
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present
      become_user: postgres

    - name: Create database user
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "ALL/{{ db_name }}"
        state: present
      become_user: postgres

    - name: Create users table
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        query: |
          CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            username VARCHAR(50) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          )
      become_user: postgres

  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted
