---
- name: Deploy DB
  hosts: db
  become: yes

  tasks:
    - name: Ensure system is up to date
      yum:
        name: "*"
        state: latest
      ignore_errors: yes

    - name: Install MariaDB server from AppStream
      yum:
        name: mariadb-server
        state: present

    - name: Enable and start MariaDB service
      systemd:
        name: mariadb
        enabled: yes
        state: started

    - name: Create database for backend app
      mysql_db:
        name: backenddb
        state: present
        login_user: root

    - name: Create DB user for backend app
      mysql_user:
        name: backenduser
        password: "backendpass123"
        priv: "backenddb.*:ALL"
        host: "%"
        state: present
        login_user: root
