---
- name: Configure PostgreSQL DB
  hosts: db
  become: yes

  tasks:
    - name: Ensure EPEL repo is enabled
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: Install PostgreSQL 14 server
      ansible.builtin.yum:
        name:
          - postgresql-server
          - postgresql
        state: present

    - name: Initialize PostgreSQL database
      ansible.builtin.command:
        cmd: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Ensure PostgreSQL service is enabled and started
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes

    - name: Allow password authentication in pg_hba.conf
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32\s+ident'
        line: 'host    all             all             0.0.0.0/0               md5'
        state: present

    - name: Listen on all interfaces
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^#listen_addresses ='
        line: "listen_addresses = '*'"

    - name: Restart PostgreSQL to apply configuration
      ansible.builtin.service:
        name: postgresql
        state: restarted

    - name: Create backend database
      community.postgresql.postgresql_db:
        name: backenddb
        encoding: UTF8
        state: present

    - name: Create backend DB user
      community.postgresql.postgresql_user:
        name: backenduser
        password: backendpass123
        priv: "backenddb:ALL"
        state: present
